READ FILES
```{r}
library(dplyr) #  Library import
df <- read.csv('imdb_movies.csv', na.strings = '', stringsAsFactors = T) # File reading
head(df)
```

```{r}
# Rename Columns
colnames(df) = c("Filme", "DataLancamento", "Score", "Categorias", "Sinopse", "Atores", "Titulo", "Status", "Lingua", "Orcamento", "Lucro", "Pais")
head(df)
```
```{r}
# Columns Names
colnames(df)
```

Limpeza dos dados
```{r}
# Importing the library to manipulate the dataframe
library(tidyverse)

df_genero <- data.frame(df$Categorias) # Variable receives the values of the Categories column

# Extract the first word before the comma to a new column in the dataframe (df_genero)
df <- df %>%
  mutate(Genero = str_extract(df$Categorias, "\\w+"))
df
```
```{r}
# Transform the class to Factor of the created column (Easier handling)
df$Genero <- factor(df$Genero)
df
```
```{r}
# Remove Columns
df <- subset(df, select = -c(Categorias, Sinopse, Atores, Titulo))
df
```
```{r}
# Data overview
summary(df)

```
Tratamento dos dados
```{r}
# Create a new variable that only receives the data that we are going to analyze
# Here we remove all Scores == 0
# Movies with Score == 0 were not released
dados <- df[df$Score != 0, ]
dados
# Remove df from memory
rm(df)
```

```{r}
# Data overview
glimpse(dados)
```

```{r}
# Change the DataLancamento column to the Date format
dados$DataLancamento <- as.Date(dados$DataLancamento, format = "%m/%d/%Y")

# We added two new columns, one that will receive the launch year and the other the launch month
dados <- dados %>% mutate(AnoLancamento = format(DataLancamento, "%Y"),
                          MesLancamento = format(DataLancamento, "%m"))
# Checking...
glimpse(dados)
```

```{r}
# Checking for NA values
dados[!complete.cases(dados),]
```
```{r}
# How many NA values exists
# 44 NA's values
summary(dados$Genero)
```
```{r}
# Deleting the NA values
dados <- na.omit(dados)

# Checking...
dados[!complete.cases(dados),]
```


```{r}
# Lucro column overview
summary(dados$Lucro)
```

```{r}
# We noticed that the existence of values == 0 in the recipe is an error
# This means that the movie has not yet been released in theaters
# Remove values equal to 0 from the score column
dados <- subset(dados, dados$Lucro != 0)
# Checking...
summary(dados$Lucro)
```
GRAPHIC ANALYSIS
```{r}
# View the data
head(dados)
```
```{r}
# Data overview
summary(dados)
```

```{r}
# Boxplot Score
library(ggplot2)
ggplot(dados, aes(y = Score, x = "")) + #  y = Score column  and x = "" (single group)
  geom_boxplot(width = 0.6, fill = "grey90", outlier.shape = 1, outlier.size =  2) + # Style the Boxplot 
  geom_errorbar(stat = "boxplot", width = 0.2) + # Add error bar (Limits)
  geom_point(stat = "summary", fun = "mean", shape = 4, size = 3, color = "red") + # Add an X in the boxplot media
  labs(y = "Avaliação", x = "Filmes") # Names x and y axis
```
```{r}
# Boxplot Score by Gender
ggplot(dados, aes(y = Score, x = Genero)) +  #  y = Score column  and x = Gender column 
  geom_boxplot(aes(fill = Genero), width = 0.6,outlier.shape = 1, outlier.size =  2, show.legend = F) + # Boxplot 
  geom_errorbar(stat = "boxplot", width = 0.2) + # Add error bar (Limits)
  geom_point(stat = "summary", fun = "mean", shape = 4, size = 3, color = "red") +# Add an X in the boxplot media
  labs(y = "Avaliação", x = "Gênero", size = 3) # Names x and y axis
```




```{r}
# Orçamento column overview
summary(dados$Orcamento)
```

```{r}
library(ggrastr) # Separate overlapping data 
  ggplot(dados, aes(y = Orcamento, x = "")) + #  y = Orcamento column  and x = "" (single group) 
  geom_boxplot_jitter(width = 0.6, fill = "grey90", outlier.shape = 1, outlier.size =  2, # Boxplot and use the library ggrastr to separate the outliers
                      outlier.jitter.height = 0, outlier.jitter.width = 0.5) +
  geom_errorbar(stat = "boxplot", width = 0.2) + # Add error bar (Limits)
  geom_point(stat = "summary", fun = "mean", shape = 4, size = 3, color = "red") + # Add an X in the boxplot media
  labs(y = "Orçamento", x = "Filmes") # Names x and y axis
```
```{r}
# Orçamento column overview
summary(dados$Lucro)
```

```{r}
ggplot(dados, aes(y = Lucro, x = "")) + #  y = Lucro column  and x = "" (single group) 
  geom_boxplot_jitter(width = 0.6, fill = "grey90", outlier.shape = 1, outlier.size =  2, # Boxplot and use the library ggrastr to separate the outliers
                      outlier.jitter.height = 0, outlier.jitter.width = 0.5) +
  geom_errorbar(stat = "boxplot", width = 0.2) + # Add error bar (Limits)
  geom_point(stat = "summary", fun = "mean", shape = 4, size = 3, color = "red") + # Add an X in the boxplot media
  labs(y = "Lucro", x = "Filmes") # Names x and y axis

```

```{r}
ggplot(data = dados) +
  geom_point(aes(x = Orcamento, y = Lucro, color = Genero), size = 2) + # Scatter plot
  labs(title = 'Dispersão dos Filmes', y = 'Lucro (Bilhões)') + # Name Title
  geom_smooth(aes(x = Orcamento, y = Lucro), method = "lm", se = FALSE, color = "black", linewidth = 0.5) + # Add tendency line
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "US$")) + # Add the dollar prefix on x and y axis
  scale_x_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "US$")) +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 15), plot.title = element_text(size = 14, face = "bold"))  # Increase axis names and values

```

```{r}
dados %>% filter(Genero == "Action") %>% # Action genre scatter plot
  ggplot(aes(x = Orcamento, y = Lucro)) + 
  labs(title = 'Dispersão Filmes de Ação') +
  geom_point(color = "#07393c",size = 2) + # Change de color point
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.5) + # Add tendency line
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "US$")) +
  scale_x_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "US$")) +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12), plot.title = element_text(size = 14, face = "bold"))  # Increase axis names and values

  
```

```{r}
dados %>% filter(Genero == "Drama") %>% # Adventure genre scatter plot
  ggplot(aes(x = Orcamento, y = Lucro)) + 
  labs(title = 'Dispersão Filmes de Drama') +
  geom_point(color = "#2c666e",size = 2) + # Change de color point
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.5) + # Add tendency line
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",")) +
  scale_x_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",")) +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12), plot.title = element_text(size = 14, face = "bold"))  # Increase axis names and values

```

```{r}
dados %>% filter(Genero == "Comedy") %>% # Animation genre scatter plot
  ggplot(aes(x = Orcamento, y = Lucro)) + 
  labs(title = 'Dispersão Filmes de Comédia') +
  geom_point(color = "#90ddf0",size = 2) + # Change de color point
  geom_smooth(method = "lm", se = FALSE, color = "black", linewidth = 0.5) + # Add tendency line
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",")) +
  scale_x_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",")) + 
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12), plot.title = element_text(size = 14, face = "bold"))  # Increase axis names and values

  
```


```{r}
ggplot(data = dados, aes(x = Genero, y = Lucro/1e9)) + # Highest earnings by gender
  geom_point(size = 5, color = "#072ac8", stat = "summary", fun = "max") + # Change color point
  labs(y = 'Lucro em Bilhões (US$)',  x = 'Gênero', title = 'Filme mais lucrativo por Gênero') + # Names axis and title
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",",prefix = "US$")) +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 15), plot.title = element_text(size = 14, face = "bold"))  # Increase axis names and values
```
```{r} 
# Barplot of number of movies by genre
ggplot(data = dados) +
  geom_bar(aes(x = fct_infreq(Genero), after_stat(count), fill = Genero), show.legend = F) + # Count how many movies by each genre
  labs(y = 'Quantidade de filmes', x = 'Gênero', title = 'Quantidade de Filmes Lançados por Gênero') + # Names axis and title
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 15), plot.title = element_text(size = 14, face = "bold")) # Increase axis names and values
```

```{r}
# Line graph of number of movies per year
ggplot(data = dados) +
  geom_line(aes(x = as.numeric(AnoLancamento), group = 1), stat = "count") +  # Count how many movies by year
  labs(y = "Quantidade de filmes", x = "Ano de lançamento", title = "Filmes Lançados por Ano") +
  scale_x_continuous(breaks = seq(min(dados$AnoLancamento), max(dados$AnoLancamento), by = 10)) + # Change the x-axis scale
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 15), plot.title = element_text(size = 14, face = "bold")) # Increase axis names and values
```
```{r}
# Limit the graph between the years 2000 to 2023
ggplot(data = dados) +
  geom_line(aes(x = as.numeric(AnoLancamento), group = 1), stat = "count") +
  labs(y = "Quantidade de filmes", x = "Ano de lançamento", title = "Filmes Lançados por Ano (1990 - 2023)") +
  scale_x_continuous(breaks = seq(min(dados$AnoLancamento), max(dados$AnoLancamento), by = 10)) +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 15),
        plot.title = element_text(size = 14, face = "bold"))  +  # Increase axis names and values
  coord_cartesian(xlim = c(1990, 2023))
```


```{r}
# Most profitable movies
options(scipen = 999) # Remove the high numbers
maior_lucro <- dados %>% select(Filme, Lucro) # Select only Film and Lucro columns from dataset
maior_lucro <- subset(maior_lucro, !duplicated(Lucro)) %>% arrange(desc(Lucro)) %>% head(7) # Eliminates duplicate data and order the datas
maior_lucro %>% head(7)
```


```{r}
# Generates the barblot of the most profitable movies
ggplot(maior_lucro, aes(x = reorder(Filme, -Lucro), y = Lucro/1e9, fill = Filme)) +
  geom_bar(stat = "identity", width = 0.5) + # Calculate the sum of the variable y, grouped by the variable x and use bars to display the sums.
  labs(title = "Filmes Mais Lucrativos", x = "Filme", y = "Lucro (Bilhões)") +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 13), plot.title = element_text(size = 14, face = "bold"), 
  legend.position = "none") +  # Increase axis names and values
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "US$")) 
  
```
```{r}
# Profits by countries
lucro_pais <- dados %>% select(Lucro, Pais) # Select only Lucro and Pais columns from dataset
lucro_pais <- lucro_pais$Lucro
lucro_pais <- aggregate(Lucro ~ Pais, data = dados, FUN = sum) %>% arrange(desc(Lucro)) %>% head(5) # Add the profit for each country
lucro_pais
```

```{r}
# Generates the barblot of the most profits by countries
ggplot(lucro_pais, aes(x = reorder(Pais, -Lucro), y = Lucro/1e9 , fill = Pais)) +
  geom_bar(stat = "identity", width = 0.5) +  # Calculate the sum of the variable y, grouped by the variable x and use bars to display the sums.
  labs(title = "Países Mais Lucrativos", x = "País", y = "Lucro (Bilhões)") +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 13), plot.title = element_text(size = 14, face = "bold"), 
  legend.position = "none") +  # Increase axis names and values
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",",prefix = "US$")) +
  coord_cartesian(ylim = c(0, 1000))
```
```{r}
# All movies score column plot
dados %>% # Take the data
group_by(Score) %>% # Group by score
count(Score)%>% # Count how many scores for each values
ggplot() + 
  geom_col(aes(x= Score, y=n, fill= Score))+ # Plot the column plot
labs(title = 'Filmes por Score', y = 'Quantidade de Filmes') 
```





